# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e6020fc309a8135414da7e2ea71a6d8785d0910c74e7b84d111749367a9f016bbb58da366912a92e40f1c09e7a3a6de0ed5c72f4078d337d1bb880010ffeed0

test:
  secret_key_base: 3638f2b5ac2c0e048bb7e9de2ea6986c3d82be6100749ba077e04958ebe57d9ca850a8ec4b19f8d4064033d0453c604c7f1be19d8af5558af2cd8e1ab899a173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
